
class FaceTrackingConstants:

    EYE_AR_THRESH = 0.2
    EYEBROW_DIST_THRESH = 27
    MAR_THRESH = 0.1
    CONSECUTIVE_FRAMES = 2
    BLINK_COUNTER = 0
    BROW_COUNTER = 0
    MAR_COUNTER = 0
    TOTAL_BLINKS = 0 