
class FaceTrackingConstants:

    EYE_AR_THRESH = 0.2
    EYEBROW_DIST_THRESH = 1.05
    MAR_THRESH = 0.37
    CONSECUTIVE_FRAMES = 1
    BLINK_COUNTER = 0
    BROW_COUNTER = 0
    MAR_COUNTER = 0
    TOTAL_BLINKS = 0 